name: Syntax Validation
on: [push, workflow_dispatch]

jobs:
  syntax-check:
    name: vale
    runs-on: ubuntu-latest

    steps:
        - name: Checkout this repository
          uses: actions/checkout@main

        - name: Create the folders
          run: mkdir -p styles && mkdir -p styles/Custom && mkdir -p styles/Vocab && mkdir -p styles/Vocab/base

        - name: Download .vale.ini
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/.vale.ini

        - name: Download Custom Style ignore.txt
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/styles/Custom/ignore.txt -O styles/Custom/ignore.txt

        - name: Download Custom Style spelling.yml
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/styles/Custom/spelling.yml -O styles/Custom/spelling.yml

        - name: Download Custom Style substitutions.yml
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/styles/Custom/substitutions.yml -O styles/Custom/substitutions.yml

        - name: Download base Vocab accept.txt
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/styles/Vocab/base/accept.txt -O styles/Vocab/base/accept.txt

        - name: Download base Vocab reject.txt
          run: wget https://raw.githubusercontent.com/fharper/gh-configs/main/styles/Vocab/base/reject.txt -O styles/Vocab/base/reject.txt

        - name: Validate the syntax
          uses: errata-ai/vale-action@reviewdog
          with:
            reporter: github-check
            fail_on_error: true
            vale_flags: "--config=.vale.ini"
